### ISSUE TITLE
Fix watch not re-running the tests correctly

### ISSUE THREAD

**Issue by RadicalZephyr** [RadicalZephyr/boot-junit#4]
I really thought running inside of a pod would totally fix it, but I guess not.  Maybe it's because I'm loading java classes through java mechanisms, so the isolated classloader from the pod is being circumvented?

**Comment by daveyarwood** [comment]
Does `watch` come before `javac` in the pipeline?

It seems like it's working correctly for me when I do `boot watch javac junit`, but I haven't dived too deeply yet.

**Comment by RadicalZephyr** [comment]
It will totally re-run the tests, but if you change the tests, it's clear the new code is not actually being run.  You can see this most clearly when you have a test that you intentionally make fail i.e. `assertEquals(true, false)` and it doesn't fail...

I actually do have a fix for this that involves mucking with how I load the jUnit test classes and recompiling them inside the `junit` task, but it's ugly and hackish and it doesn't integrate in a nice way with boot itself.  Which is possibly actually already live on the `dev` branch...

**Comment by RadicalZephyr** [comment]
Just had an interesting thought about how to handle this far less hackishly than my first attempt using the dynamic java recompiler from virgil.

As long as jUnit tests are run inside of a pod and the classes are loaded explicitly with the Clojure DynamicClassLoader, then getting a new pod will mean we actually reload the class from the newest compiled source.  That is, if pod pools are guaranteed to always give you a fresh worker pod...

**Comment by RadicalZephyr** [comment]
Which micha has confirmed is true. Done.

**Comment by RadicalZephyr** [comment]
I guess just running the tests in a pod was actually enough? So this has been fixed for a while... 🤦‍♂️
